# Generated by Django 3.0.7 on 2020-11-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_material_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
