# Generated by Django 3.0.7 on 2020-11-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20201125_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
    ]
