# Generated by Django 3.0.7 on 2020-12-07 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_emails'),
        ('material', '0004_remove_material_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier'),
        ),
    ]
