# Generated by Django 3.0.7 on 2020-12-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='emails',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
