# Generated by Django 3.0.7 on 2020-11-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_remove_material_quantity'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='material',
            field=models.ManyToManyField(to='material.Material'),
        ),
    ]
