# Generated by Django 3.0.7 on 2020-11-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_receive_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='material',
        ),
        migrations.AddField(
            model_name='receive',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=100),
            preserve_default=False,
        ),
    ]
