# Generated by Django 3.0.7 on 2020-12-03 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20201128_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='order_by',
        ),
        migrations.AddField(
            model_name='receive',
            name='order_by',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
