# Generated by Django 3.0.7 on 2020-12-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201203_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancel', 'cancel'), ('complete', 'complete')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
